version: "3.8"


# GUARDAR DATOS EMQX EN CARPETAS; BACKUP EN 2 TIEMPOS
#volumes:
#  vol-emqx-data:
#    name: foo-emqx-data
#  vol-emqx-etc:
#    name: foo-emqx-etc
#  vol-emqx-log:
#    name: foo-emqx-log

################################################################################################################    

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment: 
      TZ: "Europe/Madrid"
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"

    # COPIA DE SEGURIDAD AUTOMÁTICA EN CASO DE QUE EL SISTEMA DOCKER SE CAIGA. 
    # IGUALMENTE HABRÍA QUE MIGRAR LA DB DE DATOS DE USUSRAIO Y SU CONFIG A MONGO ATLAS.
    volumes:
      - ./mongodata:/data/db

    ports:
      - 27017:27017
 
  #####################################   
 
  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always
    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8085:8081
#    volumes:
#      - vol-emqx-data:/opt/emqx/data
#      - vol-emqx-etc:/opt/emqx/etc
#      - vol-emqx-log:/opt/emqx/log 
    links:
      - mongo
    environment: 
      EMQX_NAME: simo-iot
      EMQX_HOST: 127.0.0.1 
      TZ: "Europe/Madrid" 


      # CREDENCIALES
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "12345678"

      # EMQX AUTH
      EMQX_ALLOW_ANONYMOUS: "false"
      # NO DEJAR QUE SE SUSCRIBA UN USUARIO A CUALQUIER TOPIC
      EMQX_NOMATCH: "deny"

      # MONGO - - - CONEXIÓN
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

      EMQX_AUTH__MONGO__SERVER: "mongo:27017"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "devuser"
      EMQX_AUTH__MONGO__PASSWORD: "devpassword"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "iotgl"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      ## HABILITAR ACL query (ACCESS CONTROL LIST)
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO_ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO_ACL_QUERY__SELECTOR: "username=%u"

      # Activar por defecto al iniciar el contenedor EMQX
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard, emqx_auth_mongo"


      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000